version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commnads:
      - ufw enable
      - ufw allow 8080
  pre_build:
    commands:
      - apt update
      - apt-get install -y python3
      - apt-get install -y python3-venv
      - python3 -m venv env
      - source ./env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - flask run --host=0.0.0.0 --port=8080
